micronaut:
  application:
    name: cabs-k
datasources:
  default:
    url: jdbc:h2:mem:~/cabs-k-test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
